### ISSUE TITLE
cfde-submit raises exceptions when given corrupted archives

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#22]
Results in the stack trace:

```
Error while starting Flow: UnboundLocalError("local variable 'pkg' referenced before assignment")
Traceback (most recent call last):
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/datapackage/helpers.py", line 53, in retrieve_descriptor
    the_descriptor = json.load(f)
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nick/globus/cfde/cfde-submit/cfde_submit/client.py", line 77, in ts_validate
    pkg = Package(descriptor=data_path, strict=True)
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/datapackage/package.py", line 102, in __init__
    descriptor = helpers.retrieve_descriptor(descriptor)
  File "/Users/nick/anaconda3/envs/cfde-submit/lib/python3.9/site-packages/datapackage/helpers.py", line 66, in retrieve_descriptor
    six.raise_from(exceptions.DataPackageException(message), error)
  File "<string>", line 3, in raise_from
datapackage.exceptions.DataPackageException: Unable to parse JSON at "/Users/nick/globus/cfde/cfde-submit/KF_C2M2_submission.tgz". 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by NickolausDS** [comment]
This appeared to be a problem with the dataset I was using. I might add a client-side message to tell the user the archive is not valid.
