### ISSUE TITLE
Python error on run with explicit dcc id

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/submission-workflow#28]
This is starting with a fresh install of cfde-submit 0.1.4 from PyPI

```
cfde-submit run --dcc-id cfde_registry_dcc:kidsfirst --service-instance dev KidsFirst_submission__2020_10/KF_C2M2_submission.tgz 
/usr/local/bin/bagit.py:629: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not manifest_filename.find("tagmanifest-") is -1:
Traceback (most recent call last):
  File "/usr/local/bin/cfde-submit", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cfde_submit/main.py", line 96, in run
    if save_dcc:
UnboundLocalError: local variable 'save_dcc' referenced before assignment
```

**Comment by NickolausDS** [comment]
Fixed
