### ISSUE TITLE
cfde-submit login Authentication error

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#44]
I feel like I should point out here that I'm trying to use this as I think our users will for testing purposes. 

I tried this as both my fully auth'd identity (achar@ucdavis.edu) and as my dummy account for testing that currently doesn't have any privileges. I get the same error both ways. Both let me log out, so the login seems to have worked. 

```
(cfdesubmit) (base) amandas-mbp-2:~ amanda$ cfde-submit login
Running on service 'staging'
Starting login with Globus Auth, press ^C to cancel.
You are authenticated and your tokens have been cached.
Traceback (most recent call last):
  File "/Users/amanda/cfdesubmit/bin/cfde-submit", line 11, in <module>
    sys.exit(cli())
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/cfde_submit/main.py", line 210, in login
    login_user(force_login, no_browser, no_local_server)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/cfde_submit/main.py", line 193, in login_user
    cfde.check()
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/cfde_submit/client.py", line 215, in check
    self.flow_client.get_flow(flow_info["flow_id"])
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/globus_automate_client/flows_client.py", line 317, in get_flow
    return self.get(path, **kwargs)
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/globus_sdk/base.py", line 217, in get
    retry_401=retry_401,
  File "/Users/amanda/cfdesubmit/lib/python3.6/site-packages/globus_sdk/base.py", line 496, in _request
    raise self.error_class(r)
globus_sdk.exc.GlobusAPIError: (404, 'Error', '{"error":{"code":"NOT_FOUND","detail":"Not found: /86453578-04b5-4c72-9188-8a6db9804135"}}\n')
(cfdesubmit) (base) amandas-mbp-2:~ amanda$
```

**Comment by DavidMichaelKelly** [comment]
Are you a member of one of the DCC submitters groups? I believe you'd need that to access the workflow

**Comment by ACharbonneau** [comment]
I am the administrator of all of the DCC submitter groups, and all the Reviewer and Approver groups. 

![image](https://user-images.githubusercontent.com/1719360/108000740-aa7e4680-6fb8-11eb-9603-d96bf57fc46f.png)
![image](https://user-images.githubusercontent.com/1719360/108000754-b1a55480-6fb8-11eb-9232-347bde1025f4.png)

**Comment by DavidMichaelKelly** [comment]
This was caused by the workflow on staging not being visible to the dcc submission groups. I reran the deploy script to update permissions which should resolve this.
