### ISSUE TITLE
Confusing error when user tries to re-prepare a bdbag submission dataset

### ISSUE THREAD

**Issue by NickolausDS** [nih-cfde/submission-workflow#62]
Issue for @ACharbonneau

If a user has previously done a `cfde-submit run foo/` on a given directory, cfde-submit will set aside a temporary location for validating the data (like `foo_e831f600893976082613d564cedbfca7f7836493/`) On a second run, it will see that temporary folder already exists and panic, telling the user they need to delete it. Full stack exception here:

```
(cfde_venv) [charbo24@dev-intel14 cfde]$ cfde-submit run --dcc-id cfde_registry_dcc:lincs LINCS-metadata/c2m2_level1 --delete-dir
Running on service 'staging'
Submit datapackage 'c2m2_level1' using cfde_registry_dcc:lincs? (y/n)? > y
The output directory must not exist. Delete '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493' to submit.
You can set delete_dir=True to avoid this issue in the future.
Traceback (most recent call last):
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/bdbag_utils.py", line 94, in get_bag
    shutil.copytree(data_path, output_dir)
  File "/opt/software/Python/3.6.4-foss-2018a/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/opt/software/Python/3.6.4-foss-2018a/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/main.py", line 106, in run
    force_http=force_http, **bag_kwargs)
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/client.py", line 309, in start_deriva_flow
    handle_git_repos=handle_git_repos, bdbag_kwargs=kwargs
  File "/mnt/ufs18/home-126/charbo24/cfde/cfde_venv/lib/python3.6/site-packages/cfde_submit/bdbag_utils.py", line 98, in get_bag
    "to avoid this issue in the future.").format(output_dir))
FileExistsError: The output directory must not exist. Delete '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493' to submit.
You can set delete_dir=True to avoid this issue in the future.
Error while starting Flow: FileExistsError("The output directory must not exist. Delete '/mnt/ufs18/home-126/charbo24/cfde/LINCS-metadata/c2m2_level1_e831f600893976082613d564cedbfca7f7836493' to submit.\nYou can set delete_dir=True to avoid this issue in the future.",)
(cfde_venv) [charbo24@dev-intel14 cfde]$
```

Instead of a stack trace, the client should simply see an error message that tells them what to do. `delete_dir=True` is a bit misleading, since that's a function invocation and not a client flag. 

Additionally, supplying the --delete-dir flag doesn't appear to work correctly.

**Comment by DavidMichaelKelly** [comment]
The --delete-dir flag only seems to control directory deletion after submission, so this error was misleading. Instead of seeing a traceback, users will now just get a message asking them to delete the directory and try again.

**Comment by ACharbonneau** [comment]
I've tried resubmitting the same package several ways and can't even trigger this error again, so I think this is fixed.
