### ISSUE TITLE
Extremely opaque role error

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/submission-workflow#70]
from here: https://github.com/nih-cfde/published-documentation/discussions/184

copy of error:

```
(cfde_venv) heathap@909c4ac4d83a c2m2 % cfde-submit login
You are already logged in
(cfde_venv) heathap@909c4ac4d83a c2m2 % cfde-submit run c2m2_submission/
Please enter the CFDE identifier for your Data Coordinating Center: cfde_registry_dcc:kidsfirst
Thank you. Would you like to save cfde_registry_dcc:kidsfirst for future submissions? (y/n)? > y
(404, 'Error', '{"error":{"code":"NOT_FOUND","detail":"Not found: /c636de1b-c7a8-4a93-bdec-ab4720328564"}}\n')
Traceback (most recent call last):
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/cfde_submit/main.py", line 96, in run
    login_user()
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/cfde_submit/main.py", line 188, in login_user
    cfde.check()
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/cfde_submit/client.py", line 221, in check
    self.flow_client.get_flow(flow_info["flow_id"])
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/globus_automate_client/flows_client.py", line 317, in get_flow
    return self.get(path, **kwargs)
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/globus_sdk/base.py", line 215, in get
    return self._request(
  File "/Users/heathap/projects/c2m2/cfde_venv/lib/python3.8/site-packages/globus_sdk/base.py", line 502, in _request
    raise self.error_class(r)
globus_sdk.exc.GlobusAPIError: (404, 'Error', '{"error":{"code":"NOT_FOUND","detail":"Not found: /c636de1b-c7a8-4a93-bdec-ab4720328564"}}\n')
Error while starting Flow: GlobusAPIError(404, 'Error', '{"error":{"code":"NOT_FOUND","detail":"Not found: /c636de1b-c7a8-4a93-bdec-ab4720328564"}}\n')
```

I am pretty sure this is extremely unfriendly error telling her that she isn't authorized to do data submissions. 

This person was added as an Approver, but not a Submitter. So I think it let her log it, because she is in the globus system, but 404'd because she doesn't actually have write access to that endpoint.

I'll change her permissions. But assuming that's the problem, this error message should say something like "unauthorized user" rather than a bunch of confusing 404 info.

**Comment by DavidMichaelKelly** [comment]
This should be resolved now in the bug fix branch

![Screenshot from 2021-03-15 13-24-31](https://user-images.githubusercontent.com/1781986/111203865-80a64880-8593-11eb-91b7-dcafa29af11e.png)

**Comment by ACharbonneau** [comment]
I need to update this bug report before closing.

**Comment by ACharbonneau** [comment]
bug report updated
